hawk/config/routes.rb
# Copyright (c) 2009-2015 Tim Serong <tserong@suse.com>
# See COPYING for license.

Rails.application.routes.draw do
  root to: "pages#index"

  regex_safe_id = /[^\^\/\[\]"<>#%{}|\\~`;?:@=&]+/

  resources :cib, only: [] do
    get "/", via: [:get, :post, :options], to: "cib#show", as: ""
    match "/", via: [:options], to: "cib#show"
    match "/apply", as: :apply, to: 'cib#apply', via: [:get, :post]
    get "/ops/:id", to: "cib#ops", as: :ops, constraints: {id: regex_safe_id }

    get "/fencing", to: "fencing#index"
    get "/fencing/edit", to: "fencing#edit"
    post "/fencing/edit", to: 'fencing#edit', defaults: { format: 'json' }

    resources :nodes, constraints: {id: regex_safe_id } do
      member do
        get :online
        get :standby
        get :maintenance
        get :ready
        get :fence
        get :clearstate
        get :events
      end
    end

    resources :resources, constraints: {id: regex_safe_id } do
      member do
        get :start
        get :stop
        get :promote
        get :demote
        get :maintenance_on
        get :maintenance_off
        get :unmigrate
        get :migrate
        get :cleanup
        get :events
        get :edit_name
        post :update_name
      end

      collection do
        get :types
        get :status
      end
    end

    resources :primitives, constraints: {id: regex_safe_id } do
      member do
        get :copy
      end
    end
    resources :templates, constraints: {id: regex_safe_id } do
      member do
        get :copy
      end
    end

    resources :constraints, constraints: {id: regex_safe_id } do
      member do
        get :events
        get :edit_name
        post :update_name
      end

      collection do
        get :types
        get :status
      end
    end

    resources :tickets, constraints: {id: regex_safe_id } do
      collection do
        get 'grant/:ticket', as: :grant, to: 'tickets#grant'
        get 'revoke/:ticket', as: :revoke, to: 'tickets#revoke'
      end
    end

    resources :clones, constraints: {id: regex_safe_id }
    resources :masters, constraints: {id: regex_safe_id }
    resources :locations, constraints: {id: regex_safe_id }
    resources :colocations, constraints: {id: regex_safe_id }
    resources :orders, constraints: {id: regex_safe_id }
    resources :groups, constraints: {id: regex_safe_id }
    resources :roles, constraints: {id: regex_safe_id }
    resources :users, constraints: {id: regex_safe_id }
    resources :tags, constraints: {id: regex_safe_id }
    resources :alerts, constraints: {id: regex_safe_id }

    resources :wizards, constraints: {id: regex_safe_id } do
      member do
        post :submit
      end
    end

    resource :config, only: [:show] do
      collection do
        get :edit
        get :meta
      end
    end
    resource :profile, only: [:edit, :update]
    resource :crm_config, only: [:edit, :update]

    resources :agents, only: [:show], constraints: { id: %r{[0-9A-Za-z:%@_\-\.\/]+} }

    resource :graph, only: [:show]

    resources :commands, only: [:index]
  end

  resources :reports, only: [:index, :destroy, :show], constraints: {id: regex_safe_id } do
    collection do
      post :generate
      post :upload
      get :running, defaults: { format: 'json' }
      get :cancel, defaults: { format: 'json' }
    end

    member do
      get :display
      get :download
      get ":transition/detail(.:format)" => "reports#detail", as: :detail, constraints: { transition: /\d+/ }
      get ":transition/cib(.:format)" => "reports#cib", as: :cib, constraints: { transition: /\d+/ }
      get ":transition/graph(.:format)" => "reports#graph", as: :graph, constraints: { transition: /\d+/ }
      get ":transition/diff(.:format)" => "reports#diff", as: :diff, constraints: { transition: /\d+/ }
      get ":transition/logs(.:format)" => "reports#logs", as: :logs, constraints: { transition: /\d+/ }
      get ":transition/pefile" => "reports#pefile", as: :pefile, constraints: { transition: /\d+/ }
    end
  end

  post '/sim/run', as: :sim_run, to: 'simulator#run', defaults: { format: 'json' }
  get '/sim/result', as: :sim_result, to: 'simulator#result', defaults: { format: 'json' }
  get '/sim/intervals/:id', as: :sim_intervals, to: 'simulator#intervals', defaults: { format: 'json' }, constraints: {id: regex_safe_id }
  get '/sim/help', as: :sim_help, to: 'simulator#help'

  resource :dashboard, only: [:show] do
    member do
      get :add
      post :add
      post :remove
    end
  end

  get "help" => "pages#help", :as => :help

  get "logout" => "sessions#destroy", :as => :logout

  get "login" => "sessions#new", :as => :login
  match 'login' => "sessions#create", via: [ :post, :options], :as => :signin
  get "login/lang/:lang" => "sessions#lang", :as => :login_lang

  # API routes (verion 1)
  # /api/v1/status
  # /api/v1/cluster
  # /api/v1/resources
  # /api/v1/resources/:id
  # /api/v1/nodes
  # /api/v1/nodes/:id

  namespace :api do
    namespace :v1 do
      match "/register", to: 'api#register', via: [:post, :options]
      resources :status, only: :index do
        collection do
          match '', via: :options, action: 'index'
        end
      end
      resources :cluster, only: :index do
        collection do
          match '', via: :options, action: 'index'
        end
      end
      resources :resources, only: [:index, :show], constraints: {id: regex_safe_id } do
        collection do
          match '', via: :options, action: 'index'
          match '', via: :options, action: 'show'
        end
      end
      resources :nodes, only: [:index, :show], constraints: {id: regex_safe_id } do
        collection do
          match '', via: :options, action: 'index'
          match '', via: :options, action: 'show'
        end
      end
    end
  end

  get "/internal/auth", to: "internal_auth#show"

  if Rails.env.production?
    match '*path' => 'errors#not_found', via: :all # if nothing else matches
  end
end

hawk/app/models/order.rb
# Copyright (c) 2009-2015 Tim Serong <tserong@suse.com>
# See COPYING for license.

class Order < Constraint
  attribute :score, String
  attribute :symmetrical, Boolean
  attribute :resources, Array[Hash]

  def resources
    @resources ||= []
  end

  def resources=(value)
    @resources = value
  end

  class << self
    def all
      super.select do |record|
        record.is_a? self
      end
    end
  end

  protected

  def shell_syntax
    [].tap do |cmd|
      cmd.push "order #{id} #{score}:"

      resources.each do |set|
        cmd.push "(" unless set[:sequential] == "true" && set[:sequential]

        set[:resources].each do |resource|
          if set[:action].blank?
            cmd.push resource
          else
            cmd.push [
              resource,
              set[:action]
            ].join(":")
          end
        end

        cmd.push ")" unless set[:sequential] == "true" && set[:sequential]
      end

      unless symmetrical
        cmd.push "symmetrical=false"
      end
    end.join(" ")
  end

  class << self
    def instantiate(xml)
      record = allocate
      record.score = xml.attributes["score"] || xml.attributes["kind"] || nil

      record.symmetrical = Util.unstring(
        xml.attributes["symmetrical"],
        true
      )

      record.resources = [].tap do |resources|
        if xml.attributes["first"]
          resources.push(
            sequential: true,
            action: xml.attributes["first-action"] || nil,
            resources: [
              xml.attributes["first"]
            ]
          )

          resources.push(
            sequential: true,
            action: xml.attributes["then-action"] || nil,
            resources: [
              xml.attributes["then"]
            ]
          )
        else
          xml.elements.each do |resource|
            set = {
              sequential: Util.unstring(resource.attributes["sequential"], true),
              action: resource.attributes["action"] || nil,
              resources: []
            }

            resource.elements.each do |el|
              set[:resources].push(
                el.attributes["id"]
              )
            end

            resources.push set
          end
        end
      end

      record
    end

    def cib_type_write
      :rsc_order
    end
  end
end

hawk/app/controllers/orders_controller.rb
# Copyright (c) 2009-2015 Tim Serong <tserong@suse.com>
# See COPYING for license.

class OrdersController < ApplicationController
  before_action :login_required
  before_action :set_title
  before_action :set_cib
  before_action :set_record, only: [:edit, :update, :destroy, :show]

  def index
    respond_to do |format|
      format.html
      format.json do
        render json: Order.ordered.to_json
      end
    end
  end

  def new
    @title = _("Create Order")
    @order = Order.new

    respond_to do |format|
      format.html
    end
  end

  def create
    normalize_params! params[:order].permit!
    @title = _("Create Order")

    @order = Order.new params[:order].permit!
    @order.resources = Util.map_value(@order.resources)

    fail CreateFailure, Util.strip_error_message(@order) unless @order.save
    post_process_for! @order

    respond_to do |format|
      format.html do
        flash[:success] = _("Constraint created successfully")
        redirect_to edit_cib_order_url(cib_id: @cib.id, id: @order.id)
      end
      format.json do
        render json: @order, status: :created
      end
    end

  rescue CreateFailure => e
    respond_to do |format|
      format.html do
        flash[:danger] = e.to_s
        render action: "new"
      end
      format.json do
        render json: @order.errors, status: :unprocessable_entity
      end
    end
  end

  def edit
    @title = _("Edit Order")

    respond_to do |format|
      format.html
    end
  end

  def update
    normalize_params! params[:order].permit!
    @title = _("Edit Order")

    if params[:revert]
      return redirect_to edit_cib_order_url(cib_id: @cib.id, id: @order.id)
    end

    respond_to do |format|
      if @order.update_attributes(params[:order].permit!)
        post_process_for! @order

        format.html do
          flash[:success] = _("Constraint updated successfully")
          redirect_to edit_cib_order_url(cib_id: @cib.id, id: @order.id)
        end
        format.json do
          render json: @order, status: :updated
        end
      else
        format.html do
          render action: "edit"
        end
        format.json do
          render json: @order.errors, status: :unprocessable_entity
        end
      end
    end
  end

  def destroy
    respond_to do |format|
      out, err, rc = Invoker.instance.crm("--force", "configure", "delete", @order.id)
      if rc == 0
        format.html do
          flash[:success] = _("Order deleted successfully")
          flash[:warning] = err unless err.blank?
          redirect_to types_cib_constraints_url(cib_id: @cib.id)
        end
        format.json do
          render json: {
            success: true,
            message: _("Order deleted successfully")
          }
        end
      else
        format.html do
          flash[:alert] = _("Error deleting %s: %s") % [@order.id, err]
          redirect_to edit_cib_order_url(cib_id: @cib.id, id: @order.id)
        end
        format.json do
          render json: { error: _("Error deleting %s: %s") % [@order.id, err] }, status: :unprocessable_entity
        end
      end
    end
  end

  def show
    respond_to do |format|
      format.json do
        render json: @order.to_json
      end
      format.any { not_found  }
    end
  end

  protected

  def set_title
    @title = _("Orders")
  end

  def set_cib
    @cib = current_cib
  end

  def set_record
    @order = Order.find params[:id]

    unless @order
      respond_to do |format|
        format.html do
          flash[:alert] = _("The order constraint does not exist")
          redirect_to types_cib_constraints_url(cib_id: @cib.id)
        end
      end
    end
  end

  def post_process_for!(record)
  end

  def normalize_params!(current)
    if params[:order][:resources].nil?
      params[:order][:resources] = []
    else
      params[:order][:resources] = params[:order][:resources].values
    end
  end

  def default_base_layout
    "withrightbar"
  end
end

hawk/app/helpers/order_helper.rb
# Copyright (c) 2009-2015 Tim Serong <tserong@suse.com>
# See COPYING for license.

module OrderHelper
  def available_order_actions
    {
      "start" => _("Start"),
      "promote" => _("Promote"),
      "demote" => _("Demote"),
      "stop" => _("Stop")
    }
  end

  def available_order_resources
    [
      @cib.resources.map{|x| x[:id]},
      @cib.templates.map{|x| x[:id]}
    ].flatten.sort do |a, b|
      a.natcmp(b, true)
    end
  end
end

hawk/app/views/orders/_form.html.erb
<div class="panel panel-default">
  <div class="panel-body" data-help-target="#rightbar > .container-fluid > #helpentries > .attrhelp">
    <%= form_for [cib, order], horizontal: true, bootstrap: true do |main_form| %>
      <%= errors_for order %>
      <% if order.new_record? %>
        <%= main_form.text_field :id, label: _("Constraint ID") %>
      <% else %>
        <%= main_form.text_field :id, label: _("Constraint ID"), readonly: true %>
      <% end %>
      <div class="form-group" data-help-filter=".row.score" id="order_score_group">
        <label class="col-sm-5 control-label" for="order_score">
          <%= _("Kind") %>
        </label>
        <div class="col-sm-7">
          <div class="input-group">
            <div class="input-group-btn">
              <button aria-haspopup="true" aria-expanded="false" data-toggle="dropdown" class="btn btn-default dropdown-toggle p-y-14" id="order_score_btn" type="button">
                <span class="caret"></span>
              </button>
              <ul class="dropdown-menu">
                <li>
                  <a data-value="Mandatory" href="#">
                    <%= _("Mandatory")%>
                  </a>
                  <a data-value="Optional" href="#">
                    <%= _("Optional")%>
                  </a>
                  <a data-value="Serialize" href="#">
                    <%= _("Serialize")%>
                  </a>
                </li>
              </ul>
            </div>
            <input class="form-control text-field" id="order_score" name="order[score]" type="text" value="<%= order.score %>"></input>
          </div>
        </div>
      </div>
      <%= main_form.select :symmetrical, :boolean_options, { include_hidden: false, include_blank: false }, id: 'order_score_symmetrical', label: _("Symmetrical") %>
      <fieldset data-constraints="<%= order.resources.to_json %>" data-constraints-available="<%= available_order_resources.to_json %>" data-constraints-selects="<%= available_order_actions.to_json %>" data-constraints-prefix="order[resources]" data-constraints-target=".content">
        <legend>
          <%= _("Resources") %>
          <span class="pull-right toggleable">
            <%= icon_tag("chevron-up") %>
          </span>
        </legend>
        <div class="content constraints"></div>
      </fieldset>
      <%= main_form.button_group do %>
        <% if order.new_record? %>
          <%= create_button(main_form, order) %>
          <%= link_to _("Back"), types_cib_constraints_path(cib_id: cib.id), class: "btn btn-default back" %>
        <% else %>
          <%= apply_button(main_form, order) %>
          <%= revert_button(main_form, order) %>
          <%= link_to _("Back"), edit_cib_config_path(cib_id: cib.id, anchor: "constraints"), class: "btn btn-default back" %>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

hawk/app/views/orders/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <h1>
      <%= icon_text "sort-amount-desc", _("Edit Order"), class: "page" %>
      <div class="pull-right">
        <div class="btn-group" role="group">
          <%= link_to icon_text("plus", _("Create")), new_cib_order_path(cib_id: @cib.id), class: "btn btn-default" %>
          <%= link_to icon_text("font", _("Rename")), edit_name_cib_constraint_path(cib_id: @cib.id, id: @order.id, source: :constraint), class: "btn btn-default", data: { toggle: :modal, target: "#modal" } %>
          <%= link_to icon_text("trash", _("Delete")), cib_order_path(cib_id: @cib.id, id: @order.id), method: "delete", class: "btn btn-default", data: { confirm: _("Are you sure you wish to delete %s?") % @order.id } %>
        </div>
      </div>
    </h1>
  </div>
  <div class="row">
    <%= render partial: "form", locals: { cib: @cib, order: @order } %>
  </div>
</div>
<%= render partial: "shared/helpsidebar", locals: { category: :constraints, help: :order, mapping: @order.help_text.merge(@order.mapping) } %>

hawk/app/views/orders/index.html.erb
<div class="container-fluid">
  <div class="row">
    <h1>
      <%= icon_text "sort-amount-desc", _("Orders"), class: "page" %>
      <div class="pull-right">
        <div class="btn-group" role="group">
          <%= link_to icon_text("plus", _("Create")), new_cib_order_path, class: "btn btn-default" %>
        </div>
      </div>
    </h1>
  </div>
  <div class="row">
    <div class="panel panel-default">
      <table class="table table-striped orders"></table>
    </div>
  </div>
</div>
<%= render partial: "shared/helpsidebar", locals: { category: :constraints, help: :order, mapping: nil } %>

hawk/app/views/orders/new.html.erb
<div class="container-fluid">
  <div class="row">
    <h1>
      <%= icon_text "sort-amount-desc", _("Create Order"), class: "page" %>
      <div class="pull-right">
        <div class="btn-group" role="group"></div>
      </div>
    </h1>
  </div>
  <div class="row">
    <%= render partial: "form", locals: { cib: @cib, order: @order } %>
  </div>
</div>
<%= render partial: "shared/helpsidebar", locals: { category: :constraints, help: :order, mapping: @order.help_text.merge(@order.mapping) } %>