hawk/config/routes.rb
# Copyright (c) 2009-2015 Tim Serong <tserong@suse.com>
# See COPYING for license.

Rails.application.routes.draw do
  root to: "pages#index"

  regex_safe_id = /[^\^\/\[\]"<>#%{}|\\~`;?:@=&]+/

  resources :cib, only: [] do
    get "/", via: [:get, :post, :options], to: "cib#show", as: ""
    match "/", via: [:options], to: "cib#show"
    match "/apply", as: :apply, to: 'cib#apply', via: [:get, :post]
    get "/ops/:id", to: "cib#ops", as: :ops, constraints: {id: regex_safe_id }

    get "/fencing", to: "fencing#index"
    get "/fencing/edit", to: "fencing#edit"
    post "/fencing/edit", to: 'fencing#edit', defaults: { format: 'json' }

    resources :nodes, constraints: {id: regex_safe_id } do
      member do
        get :online
        get :standby
        get :maintenance
        get :ready
        get :fence
        get :clearstate
        get :events
      end
    end

    resources :resources, constraints: {id: regex_safe_id } do
      member do
        get :start
        get :stop
        get :promote
        get :demote
        get :maintenance_on
        get :maintenance_off
        get :unmigrate
        get :migrate
        get :cleanup
        get :events
        get :edit_name
        post :update_name
      end

      collection do
        get :types
        get :status
      end
    end

    resources :primitives, constraints: {id: regex_safe_id } do
      member do
        get :copy
      end
    end
    resources :templates, constraints: {id: regex_safe_id } do
      member do
        get :copy
      end
    end

    resources :constraints, constraints: {id: regex_safe_id } do
      member do
        get :events
        get :edit_name
        post :update_name
      end

      collection do
        get :types
        get :status
      end
    end

    resources :tickets, constraints: {id: regex_safe_id } do
      collection do
        get 'grant/:ticket', as: :grant, to: 'tickets#grant'
        get 'revoke/:ticket', as: :revoke, to: 'tickets#revoke'
      end
    end

    resources :clones, constraints: {id: regex_safe_id }
    resources :masters, constraints: {id: regex_safe_id }
    resources :locations, constraints: {id: regex_safe_id }
    resources :colocations, constraints: {id: regex_safe_id }
    resources :orders, constraints: {id: regex_safe_id }
    resources :groups, constraints: {id: regex_safe_id }
    resources :roles, constraints: {id: regex_safe_id }
    resources :users, constraints: {id: regex_safe_id }
    resources :tags, constraints: {id: regex_safe_id }
    resources :alerts, constraints: {id: regex_safe_id }

    resources :wizards, constraints: {id: regex_safe_id } do
      member do
        post :submit
      end
    end

    resource :config, only: [:show] do
      collection do
        get :edit
        get :meta
      end
    end
    resource :profile, only: [:edit, :update]
    resource :crm_config, only: [:edit, :update]

    resources :agents, only: [:show], constraints: { id: %r{[0-9A-Za-z:%@_\-\.\/]+} }

    resource :graph, only: [:show]

    resources :commands, only: [:index]
  end

  resources :reports, only: [:index, :destroy, :show], constraints: {id: regex_safe_id } do
    collection do
      post :generate
      post :upload
      get :running, defaults: { format: 'json' }
      get :cancel, defaults: { format: 'json' }
    end

    member do
      get :display
      get :download
      get ":transition/detail(.:format)" => "reports#detail", as: :detail, constraints: { transition: /\d+/ }
      get ":transition/cib(.:format)" => "reports#cib", as: :cib, constraints: { transition: /\d+/ }
      get ":transition/graph(.:format)" => "reports#graph", as: :graph, constraints: { transition: /\d+/ }
      get ":transition/diff(.:format)" => "reports#diff", as: :diff, constraints: { transition: /\d+/ }
      get ":transition/logs(.:format)" => "reports#logs", as: :logs, constraints: { transition: /\d+/ }
      get ":transition/pefile" => "reports#pefile", as: :pefile, constraints: { transition: /\d+/ }
    end
  end

  post '/sim/run', as: :sim_run, to: 'simulator#run', defaults: { format: 'json' }
  get '/sim/result', as: :sim_result, to: 'simulator#result', defaults: { format: 'json' }
  get '/sim/intervals/:id', as: :sim_intervals, to: 'simulator#intervals', defaults: { format: 'json' }, constraints: {id: regex_safe_id }
  get '/sim/help', as: :sim_help, to: 'simulator#help'

  resource :dashboard, only: [:show] do
    member do
      get :add
      post :add
      post :remove
    end
  end

  get "help" => "pages#help", :as => :help

  get "logout" => "sessions#destroy", :as => :logout

  get "login" => "sessions#new", :as => :login
  match 'login' => "sessions#create", via: [ :post, :options], :as => :signin
  get "login/lang/:lang" => "sessions#lang", :as => :login_lang

  # API routes (verion 1)
  # /api/v1/status
  # /api/v1/cluster
  # /api/v1/resources
  # /api/v1/resources/:id
  # /api/v1/nodes
  # /api/v1/nodes/:id

  namespace :api do
    namespace :v1 do
      match "/register", to: 'api#register', via: [:post, :options]
      resources :status, only: :index do
        collection do
          match '', via: :options, action: 'index'
        end
      end
      resources :cluster, only: :index do
        collection do
          match '', via: :options, action: 'index'
        end
      end
      resources :resources, only: [:index, :show], constraints: {id: regex_safe_id } do
        collection do
          match '', via: :options, action: 'index'
          match '', via: :options, action: 'show'
        end
      end
      resources :nodes, only: [:index, :show], constraints: {id: regex_safe_id } do
        collection do
          match '', via: :options, action: 'index'
          match '', via: :options, action: 'show'
        end
      end
    end
  end

  get "/internal/auth", to: "internal_auth#show"

  if Rails.env.production?
    match '*path' => 'errors#not_found', via: :all # if nothing else matches
  end
end

hawk/app/models/master.rb
# Copyright (c) 2009-2015 Tim Serong <tserong@suse.com>
# See COPYING for license.
require 'invoker'

class Master < Resource
  attribute :child, String

  validates :child,
    presence: { message: _("No Multi-state child specified") }

  validate do |record|
    # TODO(must): Ensure children are sanitized
  end

  def mapping
    self.class.mapping
  end

  class << self
    def all
      super.select do |record|
        record.is_a? self
      end
    end

    def instantiate(xml)
      record = allocate

      record.child = if xml.elements["primitive|group"]
        xml.elements["primitive|group"].attributes["id"]
      else
        nil
      end

      record.meta = if xml.elements["meta_attributes"]
        vals = xml.elements["meta_attributes"].elements.collect do |el|
          [
            el.attributes["name"],
            el.attributes["value"]
          ]
        end

        Hash[vals]
      else
        {}
      end

      record
    end

    def cib_type
      :master
    end

    def mapping
      # TODO(must): Are other meta attributes for clone valid?
      @mapping ||= begin
        {
          "is-managed" => {
            type: "boolean",
            default: "true",
            longdesc: _("Is the cluster allowed to start and stop the resource?")
          },
          "maintenance" => {
            type: "boolean",
            default: "false",
            longdesc: _("Resources in maintenance mode are not monitored by the cluster.")
          },
          "priority" => {
            type: "integer",
            default: "0",
            longdesc: _("If not all resources can be active, the cluster will stop lower priority resources in order to keep higher priority ones active.")
          },
          "target-role" => {
            type: "enum",
            default: "Stopped",
            values: [
              "Started",
              "Stopped",
              "Master"
            ],
            longdesc: _("What state should the cluster attempt to keep this resource in?")
          },
          "clone-max" => {
            type: "integer",
            default: current_cib.nodes.length.to_s,
            longdesc: _("How many copies of the resource to start. Defaults to the number of nodes in the cluster.")
          },
          "clone-node-max" => {
            type: "integer",
            default: "1",
            longdesc: _("How many copies of the resource can be started on a single node. Defaults to 1.")
          },
          "notify" => {
            type: "boolean",
            default: "false",
            longdesc: _("When stopping or starting a copy of the clone, tell all the other copies beforehand and when the action was successful.")
          },
          "globally-unique" => {
            type: "boolean",
            default: "true",
            longdesc: _("Does each copy of the clone perform a different function?")
          },
          "ordered" => {
            type: "boolean",
            default: "false",
            longdesc: _("Should the copies be started in series (instead of in parallel)?")
          },
          "interleave" => {
            type: "boolean",
            default: "false",
            longdesc: _("Changes the behavior of ordering constraints (between clones/masters) so that instances can start/stop as soon as their peer instance has (rather than waiting for every instance of the other clone has).")
          },
          "master-max" => {
            type: "integer",
            default: "1",
            longdesc: _("How many copies of the resource can be promoted to master status.")
          },
          "master-node-max" => {
            type: "integer",
            default: "1",
            longdesc: _("How many copies of the resource can be promoted to master status on a single node.")
          }
        }
      end
    end
  end

  protected

  def update
    unless self.class.exists?(self.id, self.class.cib_type_write)
      errors.add :base, _("The ID \"%{id}\" does not exist") % { id: self.id }
      return false
    end

    begin
      merge_nvpairs("meta_attributes", meta)
      Invoker.instance.cibadmin_replace xml.to_s
    rescue NotFoundError, SecurityError, RuntimeError => e
      errors.add :base, e.message
      return false
    end
  end

  def shell_syntax
    [].tap do |cmd|
      cmd.push "ms #{id} #{child}"

      unless meta.empty?
        cmd.push "meta"

        meta.each do |key, value|
          cmd.push [
            key,
            value.shellescape
          ].join("=")
        end
      end
    end.join(" ")
  end
end

hawk/app/controllers/masters_controller.rb
# Copyright (c) 2009-2015 Tim Serong <tserong@suse.com>
# See COPYING for license.

class MastersController < ApplicationController
  before_action :login_required
  before_action :set_title
  before_action :set_cib
  before_action :set_record, only: [:edit, :update, :destroy, :show]

  def index
    respond_to do |format|
      format.html
      format.json do
        render json: Master.ordered.to_json
      end
    end
  end

  def new
    @title = _("Create Promotable resource")
    @master = Master.new
    @master.meta["target-role"] = "Stopped" if @cib.id == "live"

    respond_to do |format|
      format.html
    end
  end

  def create
    normalize_params! params[:master].permit!
    @title = _("Create Promotable resource")

    @master = Master.new params[:master].permit!

    fail CreateFailure, Util.strip_error_message(@master) unless @master.save
    post_process_for! @master

    respond_to do |format|
      format.html do
        flash[:success] = _("Promotable resource created successfully")
        redirect_to edit_cib_master_url(cib_id: @cib.id, id: @master.id)
      end
      format.json do
        render json: @master, status: :created
      end
    end

  rescue CreateFailure => e
    respond_to do |format|
      format.html do
        flash[:danger] = e.to_s
        render action: "new"
      end
      format.json do
        render json: @master.errors, status: :unprocessable_entity
      end
    end
  end

  def edit
    @title = _("Edit Promotable resource")

    respond_to do |format|
      format.html
    end
  end

  def update
    normalize_params! params[:master].permit!
    @title = _("Edit Promotable resource")

    if params[:revert]
      return redirect_to edit_cib_master_url(cib_id: @cib.id, id: @master.id)
    end

    respond_to do |format|
      if @master.update_attributes(params[:master].permit!)
        post_process_for! @master

        format.html do
          flash[:success] = _("Promotable resource updated successfully")
          redirect_to edit_cib_master_url(cib_id: @cib.id, id: @master.id)
        end
        format.json do
          render json: @master, status: :updated
        end
      else
        format.html do
          render action: "edit"
        end
        format.json do
          render json: @master.errors, status: :unprocessable_entity
        end
      end
    end
  end

  def destroy
    respond_to do |format|
      out, err, rc = Invoker.instance.crm("--force", "configure", "delete", @master.id)
      if rc == 0
        format.html do
          flash[:success] = _("Promotable resource deleted successfully")
          flash[:warning] = err unless err.blank?
          redirect_to types_cib_resources_path(cib_id: @cib.id)
        end
        format.json do
          render json: {
            success: true,
            message: _("Promotable resource deleted successfully")
          }
        end
      else
        format.html do
          flash[:alert] = _("Error deleting %s: %s") % [@master.id, err]
          redirect_to edit_cib_master_url(cib_id: @cib.id, id: @master.id)
        end
        format.json do
          render json: { error: _("Error deleting %s: %s") % [@master.id, err] }, status: :unprocessable_entity
        end
      end
    end
  end

  def show
    respond_to do |format|
      format.json do
        render json: @master.to_json
      end
      format.any { not_found  }
    end
  end

  protected

  def set_title
    @title = _("Promotable resource")
  end

  def set_cib
    @cib = current_cib
  end

  def set_record
    @master = Master.find params[:id]

    unless @master
      respond_to do |format|
        format.html do
          flash[:alert] = _("The Promotable resource (%s) does not exist") % [params[:id]]
          redirect_to types_cib_resources_path(cib_id: @cib.id)
        end
      end
    end
  end

  def post_process_for!(record)
  end

  def normalize_params!(current)
  end

  def default_base_layout
    "withrightbar"
  end
end

hawk/app/helpers/master_helper.rb
# Copyright (c) 2009-2015 Tim Serong <tserong@suse.com>
# See COPYING for license.

module MasterHelper
  def master_child_list
    @cib.resources.select do |r|
      !r.key?(:children) || (r.key?(:children) && r[:type] == "group")
    end.map{|x| x[:id]}.sort do |a, b|
      a.natcmp(b, true)
    end
  end

  def master_child_for(master)
    if master.child
      master_child_list.push(master.child).sort
    else
      master_child_list.sort
    end
  end
end

hawk/app/views/masters/_form.html.erb
<div class="panel panel-default">
  <div class="panel-body" data-help-target="#rightbar > .container-fluid > #helpentries > .attrhelp">
    <%= form_for [cib, master], horizontal: true, bootstrap: true do |main_form| %>
      <%= errors_for master %>
      <% if master.new_record? %>
        <%= main_form.text_field :id, label: _("Multi-state ID") %>
        <%= main_form.select :child, master_child_for(master), { include_hidden: false, include_blank: true }, id: nil, label: _("Child Resource") %>
      <% else %>
        <%= main_form.text_field :id, label: _("Multi-state ID"), readonly: true %>
        <%= main_form.text_field :child, label: _("Child Resource"), readonly: true %>
      <% end %>
      <fieldset data-attrlist="<%= master[:meta].to_json %>" data-attrlist-mapping="<%= master.mapping.to_json %>" data-attrlist-prefix="master[meta]" data-attrlist-target=".content">
        <legend>
          <%= _("Meta Attributes") %>
          <span class="pull-right toggleable">
            <%= icon_tag("chevron-up") %>
          </span>
        </legend>
        <div class="content"></div>
      </fieldset>
      <%= main_form.button_group do %>
        <% if master.new_record? %>
          <%= create_button(main_form, master) %>
          <%= link_to _("Back"), types_cib_resources_path(cib_id: cib.id), class: "btn btn-default back" %>
        <% else %>
          <%= apply_button(main_form, master) %>
          <%= revert_button(main_form, master) %>
          <%= link_to _("Back"), edit_cib_config_path(cib_id: cib.id), class: "btn btn-default back" %>
        <% end %>
      <% end %>
    <% end %>
  </div>
</div>

hawk/app/views/masters/edit.html.erb
<div class="container-fluid">
  <div class="row">
    <h1>
      <%= icon_text "superscript", _("Edit Multi-state"), class: "page" %>
      <div class="pull-right">
        <div class="btn-group" role="group">
          <%= link_to icon_text("plus", _("Create")), new_cib_master_path(cib_id: @cib.id), class: "btn btn-default" %>
          <%= link_to icon_text("font", _("Rename")), edit_name_cib_resource_path(cib_id: @cib.id, id: @master.id, source: :resource), class: "btn btn-default", data: { toggle: :modal, target: "#modal" } %>
          <%= link_to icon_text("trash", _("Delete")), cib_master_path(cib_id: @cib.id, id: @master.id), method: "delete", class: "btn btn-default", data: { confirm: _("Are you sure you wish to delete %s?") % @master.id } %>
        </div>
      </div>
    </h1>
  </div>
  <div class="row">
    <%= render partial: "form", locals: { cib: @cib, master: @master } %>
  </div>
</div>
<%= render partial: "shared/helpsidebar", locals: { category: :resources, help: :master, mapping: @master.help_text.merge(@master.mapping) } %>

hawk/app/views/masters/index.html.erb
<div class="container-fluid">
  <div class="row">
    <h1>
      <%= icon_text "superscript", _("Promotable Resources"), class: "page" %>
      <div class="pull-right">
        <div class="btn-group" role="group">
          <%= link_to icon_text("plus", _("Create")), new_cib_master_path, class: "btn btn-default" %>
        </div>
      </div>
    </h1>
  </div>
  <div class="row">
    <div class="panel panel-default">
      <table class="table table-striped masters"></table>
    </div>
  </div>
</div>
<%= render partial: "shared/helpsidebar", locals: { category: :resources, help: :master, mapping: nil } %>

hawk/app/views/masters/new.html.erb
<div class="container-fluid">
  <div class="row">
    <h1>
      <%= icon_text "superscript", _("Create Promotable Resource"), class: "page" %>
      <div class="pull-right">
        <div class="btn-group" role="group"></div>
      </div>
    </h1>
  </div>
  <div class="row">
    <%= render partial: "form", locals: { cib: @cib, master: @master } %>
  </div>
</div>
<%= render partial: "shared/helpsidebar", locals: { category: :resources, help: :master, mapping: @master.help_text.merge(@master.mapping) } %>