hawk/config/routes.rb
# Copyright (c) 2009-2015 Tim Serong <tserong@suse.com>
# See COPYING for license.

Rails.application.routes.draw do
  root to: "pages#index"

  regex_safe_id = /[^\^\/\[\]"<>#%{}|\\~`;?:@=&]+/

  resources :cib, only: [] do
    get "/", via: [:get, :post, :options], to: "cib#show", as: ""
    match "/", via: [:options], to: "cib#show"
    match "/apply", as: :apply, to: 'cib#apply', via: [:get, :post]
    get "/ops/:id", to: "cib#ops", as: :ops, constraints: {id: regex_safe_id }

    get "/fencing", to: "fencing#index"
    get "/fencing/edit", to: "fencing#edit"
    post "/fencing/edit", to: 'fencing#edit', defaults: { format: 'json' }

    resources :nodes, constraints: {id: regex_safe_id } do
      member do
        get :online
        get :standby
        get :maintenance
        get :ready
        get :fence
        get :clearstate
        get :events
      end
    end

    resources :resources, constraints: {id: regex_safe_id } do
      member do
        get :start
        get :stop
        get :promote
        get :demote
        get :maintenance_on
        get :maintenance_off
        get :unmigrate
        get :migrate
        get :cleanup
        get :events
        get :edit_name
        post :update_name
      end

      collection do
        get :types
        get :status
      end
    end

    resources :primitives, constraints: {id: regex_safe_id } do
      member do
        get :copy
      end
    end
    resources :templates, constraints: {id: regex_safe_id } do
      member do
        get :copy
      end
    end

    resources :constraints, constraints: {id: regex_safe_id } do
      member do
        get :events
        get :edit_name
        post :update_name
      end

      collection do
        get :types
        get :status
      end
    end

    resources :tickets, constraints: {id: regex_safe_id } do
      collection do
        get 'grant/:ticket', as: :grant, to: 'tickets#grant'
        get 'revoke/:ticket', as: :revoke, to: 'tickets#revoke'
      end
    end

    resources :clones, constraints: {id: regex_safe_id }
    resources :masters, constraints: {id: regex_safe_id }
    resources :locations, constraints: {id: regex_safe_id }
    resources :colocations, constraints: {id: regex_safe_id }
    resources :orders, constraints: {id: regex_safe_id }
    resources :groups, constraints: {id: regex_safe_id }
    resources :roles, constraints: {id: regex_safe_id }
    resources :users, constraints: {id: regex_safe_id }
    resources :tags, constraints: {id: regex_safe_id }
    resources :alerts, constraints: {id: regex_safe_id }

    resources :wizards, constraints: {id: regex_safe_id } do
      member do
        post :submit
      end
    end

    resource :config, only: [:show] do
      collection do
        get :edit
        get :meta
      end
    end
    resource :profile, only: [:edit, :update]
    resource :crm_config, only: [:edit, :update]

    resources :agents, only: [:show], constraints: { id: %r{[0-9A-Za-z:%@_\-\.\/]+} }

    resource :graph, only: [:show]

    resources :commands, only: [:index]
  end

  resources :reports, only: [:index, :destroy, :show], constraints: {id: regex_safe_id } do
    collection do
      post :generate
      post :upload
      get :running, defaults: { format: 'json' }
      get :cancel, defaults: { format: 'json' }
    end

    member do
      get :display
      get :download
      get ":transition/detail(.:format)" => "reports#detail", as: :detail, constraints: { transition: /\d+/ }
      get ":transition/cib(.:format)" => "reports#cib", as: :cib, constraints: { transition: /\d+/ }
      get ":transition/graph(.:format)" => "reports#graph", as: :graph, constraints: { transition: /\d+/ }
      get ":transition/diff(.:format)" => "reports#diff", as: :diff, constraints: { transition: /\d+/ }
      get ":transition/logs(.:format)" => "reports#logs", as: :logs, constraints: { transition: /\d+/ }
      get ":transition/pefile" => "reports#pefile", as: :pefile, constraints: { transition: /\d+/ }
    end
  end

  post '/sim/run', as: :sim_run, to: 'simulator#run', defaults: { format: 'json' }
  get '/sim/result', as: :sim_result, to: 'simulator#result', defaults: { format: 'json' }
  get '/sim/intervals/:id', as: :sim_intervals, to: 'simulator#intervals', defaults: { format: 'json' }, constraints: {id: regex_safe_id }
  get '/sim/help', as: :sim_help, to: 'simulator#help'

  resource :dashboard, only: [:show] do
    member do
      get :add
      post :add
      post :remove
    end
  end

  get "help" => "pages#help", :as => :help

  get "logout" => "sessions#destroy", :as => :logout

  get "login" => "sessions#new", :as => :login
  match 'login' => "sessions#create", via: [ :post, :options], :as => :signin
  get "login/lang/:lang" => "sessions#lang", :as => :login_lang

  # API routes (verion 1)
  # /api/v1/status
  # /api/v1/cluster
  # /api/v1/resources
  # /api/v1/resources/:id
  # /api/v1/nodes
  # /api/v1/nodes/:id

  namespace :api do
    namespace :v1 do
      match "/register", to: 'api#register', via: [:post, :options]
      resources :status, only: :index do
        collection do
          match '', via: :options, action: 'index'
        end
      end
      resources :cluster, only: :index do
        collection do
          match '', via: :options, action: 'index'
        end
      end
      resources :resources, only: [:index, :show], constraints: {id: regex_safe_id } do
        collection do
          match '', via: :options, action: 'index'
          match '', via: :options, action: 'show'
        end
      end
      resources :nodes, only: [:index, :show], constraints: {id: regex_safe_id } do
        collection do
          match '', via: :options, action: 'index'
          match '', via: :options, action: 'show'
        end
      end
    end
  end

  get "/internal/auth", to: "internal_auth#show"

  if Rails.env.production?
    match '*path' => 'errors#not_found', via: :all # if nothing else matches
  end
end

hawk/app/views/resources/edit_name.html.erb
<div class="container-fluid">
  <form action="<%= update_name_cib_resource_path(cib_id: @cib.id, source: @source) %>" class="form-horizontal" id="rename-resource" method="post" role="form">
    <div class="modal-header">
      <h3 class="modal-title">
        <%= _("Rename Resource") %>
      </h3>
    </div>
    <div class="modal-body">
      <input name="<%= request_forgery_protection_token.to_s %>" type="hidden" value="<%= form_authenticity_token %>"></input>
      <input name="source" type="hidden" value="<%= @source %>"></input>
      <div class="form-group">
        <label class="col-sm-5 control-label" for="from">
          <%= _("Rename") %>
        </label>
        <div class="col-sm-7">
          <input class="form-control text-field" id="from" name="id" readonly="readonly" type="text" value="<%= @resource.id %>"></input>
        </div>
      </div>
      <div class="form-group">
        <label class="col-sm-5 control-label" for="to">
          <%= _("To") %>
        </label>
        <div class="col-sm-7">
          <input class="form-control text-field" id="to" name="to" type="text" value="<%= @resource.id %>"></input>
        </div>
      </div>
    </div>
    <div class="modal-footer">
      <button class="btn btn-default" data-dismiss="modal" type="button">
        <%= _("Cancel") %>
      </button>
      <button class="btn btn-primary" type="submit">
        <%= icon_text "save", _("Rename") %>
      </button>
    </div>
  </form>
</div>

hawk/app/views/resources/events.html.erb
<% if request.xhr? %>
  <div class="modal-header">
    <button class="close" data-dismiss="modal" type="button">
      <span aria-hidden="true">
        &times;
      </span>
      <span class="sr-only">
        <%= _("Close") %>
      </span>
    </button>
    <h3 class="modal-title">
      <%= icon_text "history", _("Recent events: %{name}" % { name: @resource.id }), class: "page" %>
    </h3>
  </div>
  <div class="modal-body">
    <table data-toggle="table" data-url='<%= cib_ops_path("#{@resource.id},*", cib_id: current_cib, format: "json") %>' data-sortable='true' data-sort-name='last_rc_change' data-sort-order='desc' data-row-style='eventsRowStyle' id="resource-events">
      <thead>
        <tr>
          <th data-field="rc" data-sortable="true" data-formatter="eventsRC">
            <%= _("RC") %>
          </th>
          <th data-field="node" data-sortable="true" >
            <%= _("Node") %>
          </th>
          <th data-field="op" >
            <%= _("Operation") %>
          </th>
          <th data-field="last_rc_change" data-sortable="true" data-sorter="eventsSorter">
            <%= _("Last Change") %>
          </th>
          <th data-field="state" >
            <%= _("State") %>
          </th>
          <th data-field="call" >
            <%= _("Call") %>
          </th>
          <th data-field="exec" >
            <%= _("Exec") %>
          </th>
          <th data-field="complete" data-formatter="eventsComplete">
            <%= _("Complete")%>
          </th>
        </tr>
      </thead>
      <tbody></tbody>
    </table>
  </div>
  <div class="modal-footer">
    <button class="btn btn-default" data-dismiss="modal" type="button">
      <%= _("Close") %>
    </button>
  </div>
<% end %>
<script>

  $("#modal,#modal-lg").find("table").bootstrapTable({
    height: Math.max(window.innerHeight - 300, 300)
  });
  function eventsRC(value, row) {
  var desc = "";
    switch (parseInt(value)) {
    case 0: desc = __("success"); break;
    case 1: desc = __('generic error'); break;
    case 2: desc = __('incorrect arguments'); break;
    case 3: desc = __('unimplemented action'); break;
    case 4: desc = __('insufficient permissions'); break;
    case 5: desc = __('installation error'); break;
    case 6: desc = __('configuration error'); break;
    case 7: desc = __('not running'); break;
    case 8: desc = __('running (master)'); break;
    case 9: desc = __('failed (master)'); break;
    default: desc = __('other'); break;
    };
    return '<abbr title="' + desc + '">' + value + '</abbr>';
  }
  function eventsRowStyle(row, index) {
    var status = parseInt(row.rc);
    if (status == 8) {
      return { classes: "info" };
    } else if (status != 0) {
      return { classes: "danger" };
    }
    return {};
  }
  function eventsSorter(a, b) {
    var fmt = 'ddd MMM DD HH:mm:SS YYYY';
    if (moment(a, fmt).isBefore(moment(b, fmt))) {
      return -1;
    } else if (moment(b, fmt).isBefore(moment(a, fmt))) {
      return 1;
    } else {
      return 0;
    }
  }
  function eventsComplete(value, row) {
    if (value == "complete") {
      return '<i class="fa fa-check"></i>';
    } else {
      return '<i class="fa fa-refresh text-muted"></i>';
    }
  }


</script>

hawk/app/views/resources/index.html.erb
<div class="container-fluid">
  <div class="row">
    <h1>
      <%= icon_text "code", _("Resources"), class: "page" %>
      <div class="pull-right">
        <div class="btn-group" role="group">
          <%= link_to icon_text("plus", _("Create")), types_cib_resources_path, class: "btn btn-default" %>
        </div>
      </div>
    </h1>
  </div>
  <div class="row">
    <div class="panel panel-default">
      <table class="table table-striped resources"></table>
    </div>
  </div>
</div>
<%= render partial: "shared/helpsidebar", locals: { category: :resources, help: :intro, mapping: nil } %>

hawk/app/views/resources/show.html.erb
<div class="container-fluid">
  <div class="modal-header">
    <h4>
      <%= icon_tag "search" %>
      <%= @resource.id %>
      <div class="pull-right text-muted small text-uppercase">
        <%= @resource.object_type %>
      </div>
    </h4>
  </div>
  <div class="modal-body">
    <div class="panel">
      <% if @resource.class.cib_type == :template || @resource.class.cib_type == :primitive %>
        <div class="row">
          <div class="col-md-5">
            <label>
              <%= _("Agent") %>
            </label>
          </div>
          <div class="col-md-7">
            <%= @resource.agent_name %>
          </div>
        </div>
      <% elsif @resource.class.cib_type == :group %>
        <div class="row">
          <div class="col-md-5">
            <label>
              <%= _("Children") %>
            </label>
          </div>
          <div class="col-md-7">
            <%= @resource.children.join(", ") %>
          </div>
        </div>
      <% elsif @resource.class.cib_type == :master || @resource.class.cib_type == :clone %>
        <div class="row">
          <div class="col-md-5">
            <label>
              <%= _("Child") %>
            </label>
          </div>
          <div class="col-md-7">
            <%= @resource.child %>
          </div>
        </div>
      <% end %>
    </div>
    <div class="row">
      <% if @resource.params.any? %>
        <div class="panel panel-default">
          <div class="panel-heading" id="r-paramcontrol" role="tab">
            <h4 class="panel-title">
              <a href="#r-params" data-toggle="collapse" role="button" aria-expanded="true" aria-controls='r-params'>
                <%= _("Parameters") %>
                <div class="pull-right">
                  <span class="caret"></span>
                </div>
              </a>
            </h4>
          </div>
          <div aria-labelledby="r-paramcontrol" class="panel-collapse collapse in" id="r-params" role="tabpanel">
            <table class="table table-condensed">
              <% @resource.params.each do |name, value| %>
                <tr>
                  <td class="col-sm-5">
                    <%= name %>
                  </td>
                  <td class="col-sm-7">
                    <%= content_tag :code, value %>
                  </td>
                </tr>
              <% end %>
            </table>
          </div>
        </div>
      <% end %>
      <% if @resource.meta.any? %>
        <div class="panel panel-default">
          <div class="panel-heading" id="r-metacontrol" role="tab">
            <h4 class="panel-title">
              <a href="#r-metas" data-toggle="collapse" role="button" aria-expanded='true' aria-controls='r-metas'>
                <%= _("Meta Attributes") %>
                <div class="pull-right">
                  <span class="caret"></span>
                </div>
              </a>
            </h4>
          </div>
          <div aria-labelledby="r-metacontrol" class="panel-collapse collapse in" id="r-metas" role="tabpanel">
            <table class="table table-condensed">
              <% @resource.meta.each do |name, value| %>
                <tr>
                  <td class="col-sm-5">
                    <%= name %>
                  </td>
                  <td class="col-sm-7">
                    <%= content_tag :code, value %>
                  </td>
                </tr>
              <% end %>
            </table>
          </div>
        </div>
      <% end %>
      <% if @resource.utilization.any? %>
        <div class="panel panel-default">
          <div class="panel-heading" id="r-utilcontrol" role="tab">
            <h4 class="panel-title">
              <a href="#r-utils" data-toggle="collapse" role="button" aria-expanded='true' aria-controls='r-utils' >
                <%= _("Utilization") %>
                <div class="pull-right">
                  <span class="caret"></span>
                </div>
              </a>
            </h4>
          </div>
          <div aria-labelledby="r-utilcontrol" class="panel-collapse collapse in" id="r-utils" role="tabpanel">
            <table class="table table-condensed">
              <% @resource.utilization.each do |name, value| %>
                <tr>
                  <td class="col-sm-5">
                    <%= name %>
                  </td>
                  <td class="col-sm-7">
                    <%= content_tag :code, value %>
                  </td>
                </tr>
              <% end %>
            </table>
          </div>
        </div>
      <% end %>
      <% if @resource.ops.any? %>
        <div class="panel panel-default">
          <div class="panel-heading" id="r-opcontrol" role="tab">
            <h4 class="panel-title">
              <a href="#r-ops" data-toggle="collapse" role="button" aria-expanded='true' aria-controls='r-ops'>
                <%= _("Operations") %>
                <div class="pull-right">
                  <span class="caret"></span>
                </div>
              </a>
            </h4>
          </div>
          <div aria-labelledby="r-opcontrol" class="panel-collapse collapse in" id="r-ops" role="tabpanel">
            <table class="table table-condensed">
              <tr>
                <th class="col-sm-5">
                  <%= _("Name") %>
                </th>
                <th class="col-sm-4">
                  <%= _("Timeout") %>
                </th>
                <th class="col-sm-3">
                  <%= _("Interval") %>
                </th>
              </tr>
              <% @resource.ops.each do |id, op| %>
                <tr>
                  <td>
                    <%= op["name"] %>
                  </td>
                  <td>
                    <% if op["timeout"] %>
                      <%= content_tag(:code, op["timeout"] || "-") %>
                    <% end %>
                  </td>
                  <td>
                    <% if op["interval"] %>
                      <%= content_tag(:code, op["interval"] || "-") %>
                    <% end %>
                  </td>
                </tr>
              <% end %>
            </table>
          </div>
        </div>
      <% end %>
      <% if @resource.running_on.any? %>
        <div class="panel panel-default">
          <div class="panel-heading" id="r-instances" role="tab">
            <h4 class="panel-title">
              <a href="#r-instances-body" data-toggle="collapse" role="button" aria-expanded='true' aria-controls='r-instances-body'>
                <%= _("Instances") %>
                <div class="pull-right">
                  <span class="caret"></span>
                </div>
              </a>
            </h4>
          </div>
          <div aria-labelledby="r-instances" class="panel-collapse collapse in" id="r-instances-body" role="tabpanel">
            <table class="table table-condensed">
              <% @resource.running_on.each do |node, state| %>
                <tr>
                  <td>
                    <%= node %>
                  </td>
                  <td>
                    <%= content_tag :code, state || "-" %>
                  </td>
                </tr>
              <% end %>
            </table>
          </div>
        </div>
      <% end %>
      <% if @resource.failed_ops.any? %>
        <div class="panel panel-default">
          <div class="panel-heading" id="r-failures" role="tab">
            <h4 class="panel-title">
              <a href="#r-failures-body" data-toggle="collapse" role="button" aria-expanded='true' aria-controls='r-failures-body'>
                <%= _("Failed Operations") %>
                <div class="pull-right">
                  <span class="caret"></span>
                </div>
              </a>
            </h4>
          </div>
          <div aria-labelledby="r-failures" class="panel-collapse collapse in" id="r-failures-body" role="tabpanel">
            <table class="table table-condensed">
              <tr>
                <th>
                  <%= _("Node") %>
                </th>
                <th>
                  <%= _("Call") %>
                </th>
                <th>
                  <%= _("Operation") %>
                </th>
                <th>
                  <%= _("Status") %>
                </th>
                <th>
                  <%= _("Reason") %>
                </th>
              </tr>
              <% @resource.failed_ops.each do |op| %>
                <tr>
                  <td>
                    <%= content_tag :code, op[:node] %>
                  </td>
                  <td>
                    <%= content_tag :code, op[:call_id] %>
                  </td>
                  <td>
                    <%= content_tag :code, op[:op] %>
                  </td>
                  <td>
                    <%= content_tag :code, op[:rc_code] %>
                  </td>
                  <td>
                    <%= content_tag :code, op[:exit_reason] %>
                  </td>
                </tr>
              <% end %>
            </table>
          </div>
        </div>
      <% end %>
      <div class="panel panel-default">
        <div class="panel-heading" id="r-constraints" role="tab">
          <h4 class="panel-title">
            <a href="#r-constraints-body" data-toggle="collapse" role="button" aria-expanded='true' aria-controls='r-constraints-body'>
              <%= _("Constraints") %>
              <div class="pull-right">
                <span class="caret"></span>
              </div>
            </a>
          </h4>
        </div>
        <div aria-labelledby="r-constraints" class="panel-collapse collapse in" id="r-constraints-body" role="tabpanel">
          <table class="table table-condensed">
            <tr>
              <th>
                <%= _("ID") %>
              </th>
              <th>
                <%= _("Type") %>
              </th>
              <th>
                <%= _("Kind") %>
              </th>
              <th>
                <%= _("To") %>
              </th>
            </tr>
            <% @resource.rsc_constraints.each do |constraint| %>
              <tr>
                <td>
                  <%= constraint[:id] %>
                </td>
                <td>
                  <%= constraint[:type] %>
                </td>
                <td>
                  <%= constraint[:score] %>
                </td>
                <td>
                  <%= constraint[:other] %>
                </td>
              </tr>
            <% end %>
          </table>
        </div>
      </div>
    </div>
  </div>
  <div class="modal-footer">
    <button class="btn btn-default" data-dismiss="modal" type="button">
      <%= _("Close") %>
    </button>
  </div>
</div>

hawk/app/views/resources/types.html.erb
<div class="container-fluid">
  <div class="row">
    <h1>
      <%= icon_text "code", _("Add Resource"), class: "page" %>
      <div class="pull-right">
        <div class="btn-group" role="group">
          <%= link_to icon_text("list-ul", _("List")), cib_resources_path, class: "btn btn-default" %>
        </div>
      </div>
    </h1>
  </div>
  <div class="row" data-help-target="#rightbar .rightbar_help > *">
    <ul class="nav nav-pills nav-stacked nav-bighelp nav-topspace">
      <li class="btn btn-default btn-lg">
        <%= link_to new_cib_primitive_path(cib_id: current_cib.id), data: { help_filter: ".primitive" } do %>
          <div class="pull-right">
            <%= icon_tag "plus-circle" %>
          </div>
          <%= icon_text "file-o", _("Primitive") %>
        <% end %>
      </li>
      <li class="btn btn-default btn-lg">
        <%= link_to new_cib_group_path(cib_id: current_cib.id), data: { help_filter: ".group" } do %>
          <div class="pull-right">
            <%= icon_tag "plus-circle" %>
          </div>
          <%= icon_text "group", _("Group") %>
        <% end %>
      </li>
      <li class="btn btn-default btn-lg">
        <%= link_to new_cib_clone_path(cib_id: current_cib.id), data: { help_filter: ".clone" } do %>
          <div class="pull-right">
            <%= icon_tag "plus-circle" %>
          </div>
          <%= icon_text "copy", _("Clone") %>
        <% end %>
      </li>
      <li class="btn btn-default btn-lg">
        <%= link_to new_cib_master_path(cib_id: current_cib.id), data: { help_filter: ".multistate" } do %>
          <div class="pull-right">
            <%= icon_tag "plus-circle" %>
          </div>
          <%= icon_text "superscript", _("Multi-state") %>
        <% end %>
      </li>
      <li class="btn btn-default btn-lg">
        <%= link_to new_cib_tag_path(cib_id: current_cib.id), data: { help_filter: ".tag" } do %>
          <div class="pull-right">
            <%= icon_tag "plus-circle" %>
          </div>
          <%= icon_text "tag", _("Tag") %>
        <% end %>
      </li >
      <% if Util.has_feature? :rsc_template %>
        <li class="btn btn-default btn-lg">
          <%= link_to new_cib_template_path(cib_id: current_cib.id), data: { help_filter: ".template" } do %>
            <div class="pull-right">
              <%= icon_tag "plus-circle" %>
            </div>
            <%= icon_text "file-text-o", _("Template") %>
          <% end %>
        </li>
      <% end %>
      <li class="btn btn-default btn-lg">
        <%= link_to new_cib_alert_path(cib_id: current_cib.id), data: { help_filter: ".alerthelp" } do %>
          <div class="pull-right">
            <%= icon_tag "plus-circle" %>
          </div>
          <%= icon_text "bullhorn", _("Alert") %>
        <% end %>
      </li>
    </ul>
  </div>
</div>
<% content_for :rightbar do %>
  <div class="container-fluid" data-spy="affix">
    <div class="row">
      <%= localized_help_for :resources, :intro %>
    </div>
    <div class="rightbar_help">
      <div class="row primitive">
        <%= localized_help_for :resources, :primitive %>
      </div>
      <div class="row group">
        <%= localized_help_for :resources, :group %>
      </div>
      <div class="row clone">
        <%= localized_help_for :resources, :clone %>
      </div>
      <div class="row multistate">
        <%= localized_help_for :resources, :master %>
      </div>
      <div class="row tag">
        <%= localized_help_for :resources, :tag %>
      </div>
      <div class="row template">
        <%= localized_help_for :resources, :template %>
      </div>
      <div class="row alerthelp">
        <%= localized_help_for :resources, :alert %>
      </div>
    </div>
  </div>
<% end %>