hawk/config/routes.rb
# Copyright (c) 2009-2015 Tim Serong <tserong@suse.com>
# See COPYING for license.

Rails.application.routes.draw do
  root to: "pages#index"

  regex_safe_id = /[^\^\/\[\]"<>#%{}|\\~`;?:@=&]+/

  resources :cib, only: [] do
    get "/", via: [:get, :post, :options], to: "cib#show", as: ""
    match "/", via: [:options], to: "cib#show"
    match "/apply", as: :apply, to: 'cib#apply', via: [:get, :post]
    get "/ops/:id", to: "cib#ops", as: :ops, constraints: {id: regex_safe_id }

    get "/fencing", to: "fencing#index"
    get "/fencing/edit", to: "fencing#edit"
    post "/fencing/edit", to: 'fencing#edit', defaults: { format: 'json' }

    resources :nodes, constraints: {id: regex_safe_id } do
      member do
        get :online
        get :standby
        get :maintenance
        get :ready
        get :fence
        get :clearstate
        get :events
      end
    end

    resources :resources, constraints: {id: regex_safe_id } do
      member do
        get :start
        get :stop
        get :promote
        get :demote
        get :maintenance_on
        get :maintenance_off
        get :unmigrate
        get :migrate
        get :cleanup
        get :events
        get :edit_name
        post :update_name
      end

      collection do
        get :types
        get :status
      end
    end

    resources :primitives, constraints: {id: regex_safe_id } do
      member do
        get :copy
      end
    end
    resources :templates, constraints: {id: regex_safe_id } do
      member do
        get :copy
      end
    end

    resources :constraints, constraints: {id: regex_safe_id } do
      member do
        get :events
        get :edit_name
        post :update_name
      end

      collection do
        get :types
        get :status
      end
    end

    resources :tickets, constraints: {id: regex_safe_id } do
      collection do
        get 'grant/:ticket', as: :grant, to: 'tickets#grant'
        get 'revoke/:ticket', as: :revoke, to: 'tickets#revoke'
      end
    end

    resources :clones, constraints: {id: regex_safe_id }
    resources :masters, constraints: {id: regex_safe_id }
    resources :locations, constraints: {id: regex_safe_id }
    resources :colocations, constraints: {id: regex_safe_id }
    resources :orders, constraints: {id: regex_safe_id }
    resources :groups, constraints: {id: regex_safe_id }
    resources :roles, constraints: {id: regex_safe_id }
    resources :users, constraints: {id: regex_safe_id }
    resources :tags, constraints: {id: regex_safe_id }
    resources :alerts, constraints: {id: regex_safe_id }

    resources :wizards, constraints: {id: regex_safe_id } do
      member do
        post :submit
      end
    end

    resource :config, only: [:show] do
      collection do
        get :edit
        get :meta
      end
    end
    resource :profile, only: [:edit, :update]
    resource :crm_config, only: [:edit, :update]

    resources :agents, only: [:show], constraints: { id: %r{[0-9A-Za-z:%@_\-\.\/]+} }

    resource :graph, only: [:show]

    resources :commands, only: [:index]
  end

  resources :reports, only: [:index, :destroy, :show], constraints: {id: regex_safe_id } do
    collection do
      post :generate
      post :upload
      get :running, defaults: { format: 'json' }
      get :cancel, defaults: { format: 'json' }
    end

    member do
      get :display
      get :download
      get ":transition/detail(.:format)" => "reports#detail", as: :detail, constraints: { transition: /\d+/ }
      get ":transition/cib(.:format)" => "reports#cib", as: :cib, constraints: { transition: /\d+/ }
      get ":transition/graph(.:format)" => "reports#graph", as: :graph, constraints: { transition: /\d+/ }
      get ":transition/diff(.:format)" => "reports#diff", as: :diff, constraints: { transition: /\d+/ }
      get ":transition/logs(.:format)" => "reports#logs", as: :logs, constraints: { transition: /\d+/ }
      get ":transition/pefile" => "reports#pefile", as: :pefile, constraints: { transition: /\d+/ }
    end
  end

  post '/sim/run', as: :sim_run, to: 'simulator#run', defaults: { format: 'json' }
  get '/sim/result', as: :sim_result, to: 'simulator#result', defaults: { format: 'json' }
  get '/sim/intervals/:id', as: :sim_intervals, to: 'simulator#intervals', defaults: { format: 'json' }, constraints: {id: regex_safe_id }
  get '/sim/help', as: :sim_help, to: 'simulator#help'

  resource :dashboard, only: [:show] do
    member do
      get :add
      post :add
      post :remove
    end
  end

  get "help" => "pages#help", :as => :help

  get "logout" => "sessions#destroy", :as => :logout

  get "login" => "sessions#new", :as => :login
  match 'login' => "sessions#create", via: [ :post, :options], :as => :signin
  get "login/lang/:lang" => "sessions#lang", :as => :login_lang

  # API routes (verion 1)
  # /api/v1/status
  # /api/v1/cluster
  # /api/v1/resources
  # /api/v1/resources/:id
  # /api/v1/nodes
  # /api/v1/nodes/:id

  namespace :api do
    namespace :v1 do
      match "/register", to: 'api#register', via: [:post, :options]
      resources :status, only: :index do
        collection do
          match '', via: :options, action: 'index'
        end
      end
      resources :cluster, only: :index do
        collection do
          match '', via: :options, action: 'index'
        end
      end
      resources :resources, only: [:index, :show], constraints: {id: regex_safe_id } do
        collection do
          match '', via: :options, action: 'index'
          match '', via: :options, action: 'show'
        end
      end
      resources :nodes, only: [:index, :show], constraints: {id: regex_safe_id } do
        collection do
          match '', via: :options, action: 'index'
          match '', via: :options, action: 'show'
        end
      end
    end
  end

  get "/internal/auth", to: "internal_auth#show"

  if Rails.env.production?
    match '*path' => 'errors#not_found', via: :all # if nothing else matches
  end
end

hawk/app/models/constraint.rb
# Copyright (c) 2009-2015 Tim Serong <tserong@suse.com>
# See COPYING for license.

class Constraint < Record
  include ActiveModel::Validations
  class CommandError < StandardError
  end

  attribute :object_type, Symbol
  validates_with ColocationValidator, if: Proc.new { |a| a.is_a? Colocation }
  validates_with OrderValidator, if: Proc.new { |a| a.is_a? Order } 

  validate do |record|
    # to validate a new record:
    # try making the shell form and running verify;commit in a temporary shadow cib in crm
    # if it fails, report errors
    if record.new_record && current_cib.live?
      cli = record.shell_syntax
      _out, err, rc = Invoker.instance.no_log do |i|
        i.crm_configure ['cib new', cli, 'verify', 'commit'].join("\n")
      end
      err.lines.each do |l|
        record.errors.add :base, l[7..-1] if l.start_with? "ERROR:"
      end if rc != 0
    end
  end

  def object_type
    self.class.to_s.downcase
  end

  class << self
    def all
      super(true)
    end

    def find(id, attr = 'id')
      rsc = super(id, attr)
      return rsc if rsc.is_a? Constraint
      raise Cib::RecordNotFound, _("Not a constraint")
    end

    def cib_type_fetch
      :constraints
    end

    def help_text
      super.merge(
        id: {
          type: "string",
          shortdesc: _("Constraint ID"),
          longdesc: _("Unique identifier for the constraint. May not contain spaces."),
          default: ""
        }
      )
    end
  end
end

hawk/app/controllers/constraints_controller.rb
# Copyright (c) 2009-2015 Tim Serong <tserong@suse.com>
# See COPYING for license.

class ConstraintsController < ApplicationController
  before_action :login_required
  before_action :set_title
  before_action :set_cib

  def index
    respond_to do |format|
      format.html
      format.json do
        render json: Constraint.all.to_json
      end
    end
  end

  def status
    respond_to do |format|
      format.json do
        render json: @cib.constraints.to_json
      end
    end
  end

  def types
    respond_to do |format|
      format.html
    end
  end

  def show
    @constraint = Constraint.find params[:id]

    respond_to do |format|
      format.html
    end
  end

  def new
    # redirect depending on type of resource
    constraint = Constraint.find params[:id]
    new_url = "new_cib_#{constraint.object_type}_url".to_sym
    redirect_to send(new_url, cib_id: @cib.id, id: params[:id])
  end

  def edit
    # redirect depending on type of resource
    constraint = Constraint.find params[:id]
    edit_url = "edit_cib_#{constraint.object_type}_url".to_sym
    redirect_to send(edit_url, cib_id: @cib.id, id: params[:id])
  end

  def edit_name
    constraint_name = params[:id]
    @source = params[:source] || "edit"
    @constraint = Constraint.find constraint_name
    respond_to do |format|
      format.html
    end
  end

  def update_name
    from = params[:id]
    to = params[:to]
    @source = params[:source] || "edit"
    @constraint = Constraint.find from

    _out, err, rc = Invoker.instance.crm_configure("rename #{from} #{to}")

    respond_to do |format|
      if rc == 0
        msg = _("Successfully renamed %{A} to %{B}") % { A: from, B: to }
        format.html do
          flash[:success] = msg
          if @source == "constraint"
            redirect_to edit_cib_constraint_url(cib_id: @cib.id, id: to)
          else
            redirect_to edit_cib_config_url(cib_id: @cib.id)
          end
        end
        format.json do
          render json: { success: true, message: msg }
        end
      else
        msg = _("Failed to rename %{A} to %{B}: %{E}") % { A: from, B: to, E: err }
        format.html do
          flash[:danger] = msg

          if @source == "constraint"
            redirect_to edit_cib_constraint_url(cib_id: @cib.id, id: from)
          else
            redirect_to edit_cib_config_url(cib_id: @cib.id)
          end
        end
        format.json do
          render json: {
            error: msg
          }, status: :unprocessable_entity
        end
      end
    end
  end

  protected

  def set_title
    @title = _("Constraints")
  end

  def set_cib
    @cib = current_cib
  end

  def default_base_layout
    if ["index", "types"].include? params[:action]
      "withrightbar"
    else
      if params[:action] == "show"
        "modal"
      else
        super
      end
    end
  end
end

hawk/app/helpers/constraints_helper.rb
# Copyright (c) 2009-2015 Tim Serong <tserong@suse.com>
# See COPYING for license.

module ConstraintsHelper
  # Gives role or action suffix
  # (":Master", ":Started", ":promote", ":start" etc.).
  def role_string(klass, hash)
    role = klass == Colocation ? hash[:role] : hash[:action]
    role ? ":#{role}" : ""
  end

  # prettify colocation or order constraint
  def rsc_set(con)
    con.resources.map {|set|
      if set[:sequential]
        set[:resources].map {|rsc|
          "<span>" + h(rsc[:id] + role_string(con.class, set)) + "</span>"
        }.join(image_tag('arrow-right.png', :alt => '&rarr;'))
      else
        "<span>" + set[:resources].map {|rsc|
          h(rsc[:id] + role_string(con.class, set))
        }.join(" ") + "</span>"
      end
    }.join(image_tag('arrow-right.png', :alt => '&rarr;'))
  end
end

hawk/app/views/constraints/edit_name.html.erb
<div class="container-fluid">
  <form action="<%= update_name_cib_constraint_path(cib_id: @cib.id, source: @source) %>" class="form-horizontal" id="rename-constraint" method="post" role="form">
    <div class="modal-header">
      <h3 class="modal-title">
        <%= _("Rename Constraint") %>
      </h3>
    </div>
    <div class="modal-body">
      <input name="<%= request_forgery_protection_token.to_s %>" type="hidden" value="<%= form_authenticity_token %>"></input>
      <input name="source" type="hidden" value="<%= @source %>"></input>
      <div class="form-group">
        <label class="col-sm-5 control-label" for="from">
          <%= _("Rename") %>
        </label>
        <div class="col-sm-7">
          <input class="form-control text-field" id="from" name="id" readonly="readonly" type="text" value="<%= @constraint.id %>"></input>
        </div>
      </div>
      <div class="form-group">
        <label class="col-sm-5 control-label" for="to">
          <%= _("To") %>
        </label>
        <div class="col-sm-7">
          <input class="form-control text-field" id="to" name="to" type="text" value="<%= @constraint.id %>"></input>
        </div>
      </div>
    </div>
    <div class="modal-footer">
      <button class="btn btn-default" data-dismiss="modal" type="button">
        <%= _("Cancel") %>
      </button>
      <button class="btn btn-primary" type="submit">
        <%= icon_text "save", _("Rename") %>
      </button>
    </div>
  </form>
</div>

hawk/app/views/constraints/index.html.erb
<div class="container-fluid">
  <div class="row">
    <h1>
      <%= icon_text "eye", _("Constraints"), class: "page" %>
      <div class="pull-right">
        <div class="btn-group" role="group">
          <%= link_to icon_text("plus", _("Create")), types_cib_constraints_path, class: "btn btn-default" %>
        </div>
      </div>
    </h1>
  </div>
  <div class="row">
    <div class="panel panel-default">
      <table class="table table-striped constraints"></table>
    </div>
  </div>
</div>
<%= render partial: "shared/helpsidebar", locals: { category: :constraints, help: :intro, mapping: nil } %>

hawk/app/views/constraints/rename.html.erb
<div class="container-fluid">
  <form action="<%= rename_cib_constraint_url(cib_id: @cib.id) %>" class="form-horizontal" id="rename-constraint" method="post" role="form">
    <div class="modal-header">
      <h3 class="modal-title">
        <%= _("Rename Constraint") %>
      </h3>
    </div>
    <div class="modal-body">
      <input name="<%= request_forgery_protection_token.to_s %>" type="hidden" value="<%= form_authenticity_token %>"></input>
      <input name="source" type="hidden" value="<%= @source %>"></input>
      <div class="form-group">
        <label class="col-sm-5 control-label" for="from">
          <%= _("Rename") %>
        </label>
        <div class="col-sm-7">
          <input class="form-control text-field" id="from" name="id" readonly="readonly" type="text" value="<%= @constraint.id %>"></input>
        </div>
      </div>
      <div class="form-group">
        <label class="col-sm-5 control-label" for="to">
          <%= _("To") %>
        </label>
        <div class="col-sm-7">
          <input class="form-control text-field" id="to" name="to" type="text" value="<%= @constraint.id %>"></input>
        </div>
      </div>
    </div>
    <div class="modal-footer">
      <button class="btn btn-default" data-dismiss="modal" type="button">
        <%= _("Cancel") %>
      </button>
      <button class="btn btn-primary" type="submit">
        <%= icon_text "save", _("Rename") %>
      </button>
    </div>
  </form>
</div>

hawk/app/views/constraints/show.html.erb
<div class="container-fluid">
  <div class="modal-header">
    <h4>
      <%= icon_tag "search" %>
      <%= _("Constraint:") %>
      <%= @constraint.id %>
      <small>
        <%= @constraint.object_type %>
      </small>
    </h4>
  </div>
  <div class="modal-body"></div>
  <div class="modal-footer">
    <button class="btn btn-default" data-dismiss="modal" type="button">
      <%= _("Close") %>
    </button>
  </div>
</div>

hawk/app/views/constraints/types.html.erb
<div class="container-fluid">
  <div class="row">
    <h1>
      <%= icon_text "eye", _("Add Constraint"), class: "page" %>
      <div class="pull-right">
        <div class="btn-group" role="group">
          <%= link_to icon_text("list-ul", _("List")), cib_constraints_path, class: "btn btn-default" %>
        </div>
      </div>
    </h1>
  </div>
  <div class="row">
    <ul class="nav nav-pills nav-stacked nav-bighelp nav-topspace" data-help-target="#rightbar .rightbar_help > *">
      <li class="btn btn-default btn-lg">
        <%= link_to new_cib_location_path(cib_id: current_cib.id), data: { help_filter: ".location" } do %>
          <div class="pull-right">
            <%= icon_tag "plus-circle" %>
          </div>
          <%= icon_text "globe", _("Location") %>
        <% end %>
      </li>
      <li class="btn btn-default btn-lg">
        <%= link_to new_cib_colocation_path(cib_id: current_cib.id), data: { help_filter: ".colocation" } do %>
          <div class="pull-right">
            <%= icon_tag "plus-circle" %>
          </div>
          <%= icon_text "tasks", _("Colocation") %>
        <% end %>
      </li>
      <li class="btn btn-default btn-lg">
        <%= link_to new_cib_order_path(cib_id: current_cib.id), data: { help_filter: ".order" } do %>
          <div class="pull-right">
            <%= icon_tag "plus-circle" %>
          </div>
          <%= icon_text "sort-amount-desc", _("Order") %>
        <% end %>
      </li>
      <li class="btn btn-default btn-lg">
        <%= link_to new_cib_ticket_path(cib_id: current_cib.id), data: { help_filter: ".ticket" } do %>
          <div class="pull-right">
            <%= icon_tag "plus-circle" %>
          </div>
          <%= icon_text "ticket", _("Ticket") %>
        <% end %>
      </li>
    </ul>
  </div>
</div>
<% content_for :rightbar do %>
  <div class="container-fluid" data-spy="affix">
    <div class="row help-title">
      <%= localized_help_for :constraints, :intro %>
    </div>
    <div class="rightbar_help">
      <div class="row location">
        <%= localized_help_for :constraints, :location %>
      </div>
      <div class="row colocation">
        <%= localized_help_for :constraints, :colocation %>
      </div>
      <div class="row order">
        <%= localized_help_for :constraints, :order %>
      </div>
      <div class="row ticket">
        <%= localized_help_for :constraints, :ticket %>
      </div>
    </div>
  </div>
<% end %>